services:
  - type: web
    name: enterprise-fraud-risk-intel
    env: docker
    plan: free # or starter
    region: singapore # or oregon, frankfurt
    healthCheckPath: /
    envVars:
      - key: DB_PATH
        value: /data/fraud_platform.db
    disk:
      name: risk_data
      mountPath: /data
      sizeGB: 1
